### ISSUE TITLE
rmdir error during file cleanup

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/ZetaHunter#37]
When running off a cluster, the cleanup steps run into an error when the tmp directory is "not empty". When running directly off a node with the same input files, ZetaHunter runs to completion.

Likely, the error is due to the delay caused in the NSF system. Maybe build in a slight delay before attempting to remove.

```
Error:
INFO  -- [2017-08-08 16:42:40.359] -- Write cytoscape files finished in 0.002100128 seconds 
/home/mcallis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:1334:in `rmdir': Directory not empty @ dir_s_rmdir - ZH_newisolates/tmp (Errno::ENOTEMPTY)
	from /home/mcallis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:1334:in `block in remove_dir1'
	from /home/mcallis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:1345:in `platform_support'
	from /home/mcallis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:1333:in `remove_dir1'
	from /home/mcallis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:1326:in `remove'
	from /home/mcallis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:688:in `block in remove_entry'
	from /home/mcallis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:1383:in `postorder_traverse'
	from /home/mcallis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:686:in `remove_entry'
	from /home/mcallis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:554:in `block in rm_r'
	from /home/mcallis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:550:in `each'
	from /home/mcallis/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:550:in `rm_r'
	from /home/mcallis/software/ZetaHunter_0.0.16/lib/utils/utils.rb:773:in `clean_up'
	from /home/mcallis/software/ZetaHunter_0.0.16/zeta_hunter.rb:525:in `block in <main>'
	from /home/mcallis/software/ZetaHunter_0.0.16/lib/core_extensions/time/time.rb:11:in `time_it'
	from /home/mcallis/software/ZetaHunter_0.0.16/zeta_hunter.rb:524:in `<main>'
```

**Comment by mooreryan** [comment]
Hopefully this will do the trick 84e81800fd5cc7ec8fca82ce762ff9930bc86cbc.

I put a two second pause in case it's the NFS issue. If that doesn't work, then ZH will now just skip trying to delete the tmp dir.
