### ISSUE TITLE
bug: reference to closed_ref_otus missing from function definition

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/ZetaHunter#38]
First time I have seen this error.

```
INFO  -- [2017-09-11 18:03:33.890] -- Find OTU file finished in 0.000146 seconds 
/Users/sean/vendor/ZetaHunter-0.0.16/lib/utils/utils.rb:676:in `block (4 levels) in assign_denovo_otus': undefined local variable or method `closed_ref_otus' for Utils:Module (NameError)
Did you mean?  closest_to_outgroups
	from /Users/sean/vendor/ZetaHunter-0.0.16/lib/utils/utils.rb:666:in `each'
	from /Users/sean/vendor/ZetaHunter-0.0.16/lib/utils/utils.rb:666:in `block (3 levels) in assign_denovo_otus'
	from /Users/sean/vendor/ZetaHunter-0.0.16/lib/utils/utils.rb:651:in `each_line'
	from /Users/sean/vendor/ZetaHunter-0.0.16/lib/utils/utils.rb:651:in `block (2 levels) in assign_denovo_otus'
	from /Users/sean/vendor/ZetaHunter-0.0.16/lib/utils/utils.rb:648:in `open'
	from /Users/sean/vendor/ZetaHunter-0.0.16/lib/utils/utils.rb:648:in `block in assign_denovo_otus'
	from /Users/sean/vendor/ZetaHunter-0.0.16/lib/utils/utils.rb:645:in `open'
	from /Users/sean/vendor/ZetaHunter-0.0.16/lib/utils/utils.rb:645:in `assign_denovo_otus'
	from /Users/sean/vendor/ZetaHunter-0.0.16/zeta_hunter.rb:479:in `block in <main>'
	from /Users/sean/vendor/ZetaHunter-0.0.16/lib/core_extensions/time/time.rb:11:in `time_it'
	from /Users/sean/vendor/ZetaHunter-0.0.16/zeta_hunter.rb:478:in `<main>'
```

Fix (ZH 0.0.16):
Add "closed_ref_otus" after line 484 in zeta_hunter.rb. Add "closed_ref_otus" after line 643 in utils.rb.

**Comment by mooreryan** [comment]
Fixed 302a401f6b82a0dfaf16815d7177379e9c95a3c9
