### ISSUE TITLE
ZH Error after last update

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/ZetaHunter#43]
Looks like something was broken while you were fixing the unit tests in the last update.

ZH won't run on the gold database file (I've used it several times to check before).

Stalls on uchime, but with "--no-check-chimeras" stalls on open reference binning (mothur distance calculations).

First run
```
seanmcastersMBP:Desktop sean$ run_zeta_hunter -i Gold_release3.fasta -o ZH_GOLDTEST -t 4



RUNNING COMMAND: docker pull mooreryan/zetahunter


Using default tag: latest
latest: Pulling from mooreryan/zetahunter
Digest: sha256:534ff7c384915c104d55f503d9e6373dbc0911ec65860f383ba949290505980f
Status: Image is up to date for mooreryan/zetahunter:latest



RUNNING COMMAND: docker run -v "$HOME:$HOME" mooreryan/zetahunter ruby /home/ZetaHunter/zeta_hunter.rb -i '/Users/sean/Desktop/Gold_release3.fasta' -o '/Users/sean/Desktop/ZH_GOLDTEST' -t '4'


DEBUG -- [2018-07-03 01:11:40.120] -- Version: 1.0.0, Copyright: 2016 - 2018 Ryan Moore, Contact: moorer@udel.edu, Website: https://github.com/mooreryan/ZetaHunter, License: GPLv3 
INFO  -- [2018-07-03 01:11:40.120] -- Temporary log file location: /ZH_2018_07_03_01_11.log.zh.txt. If ZetaHunter fails to complete, the log will be here. 
DEBUG -- [2018-07-03 01:11:40.120] -- ARGV: ["-i", "/Users/sean/Desktop/Gold_release3.fasta", "-o", "/Users/sean/Desktop/ZH_GOLDTEST", "-t", "4"] 
DEBUG -- [2018-07-03 01:11:40.121] -- Command line opts: {:inaln=>["/Users/sean/Desktop/Gold_release3.fasta"], :outdir=>"/Users/sean/Desktop/ZH_GOLDTEST", :threads=>4, :db_otu_info=>"/home/ZetaHunter/assets/db_otu_info.txt", :mask=>"/home/ZetaHunter/assets/mask.fa.gz", :db_seqs=>"/home/ZetaHunter/assets/db_seqs.fa.gz", :mothur=>"/home/ZetaHunter/bin/linux/mothur", :sortmerna=>"/home/ZetaHunter/bin/linux/sortmerna", :indexdb_rna=>"/home/ZetaHunter/bin/linux/indexdb_rna", :cluster_method=>"average", :otu_percent=>97, :check_chimeras=>true, :base=>"ZH_2018_07_03_01_11", :debug=>false, :version=>false, :help=>false, :inaln_given=>true, :outdir_given=>true, :threads_given=>true} 
INFO  -- [2018-07-03 01:11:40.167] -- Create needed directories finished in 0.0013482 seconds 
DEBUG -- [2018-07-03 01:11:40.168] -- Sample to fname map: /tmp/d20180703_1_cte5v9/misc/ZH_2018_07_03_01_11.sample_id_to_fname.txt 
INFO  -- [2018-07-03 01:11:40.168] -- Write sample to file name map finished in 0.0004367 seconds 
INFO  -- [2018-07-03 01:11:40.173] -- Unzip if needed finished in 0.0043651 seconds 
INFO  -- [2018-07-03 01:11:45.678] -- Process input data finished in 5.5046877 seconds 
INFO  -- [2018-07-03 01:11:45.682] -- Read entropy info finished in 0.0045599 seconds 
INFO  -- [2018-07-03 01:11:45.687] -- Read db OTU metadata finished in 0.0044148 seconds 
INFO  -- [2018-07-03 01:11:45.700] -- Num mask bases: 1282 
INFO  -- [2018-07-03 01:11:45.701] -- Read mask info finished in 0.01342 seconds 
INFO  -- [2018-07-03 01:11:50.301] -- Update shared gap posns with db seqs finished in 4.6000461 seconds 
INFO  -- [2018-07-03 01:11:50.302] -- Read outgroups finished in 0.0002846 seconds 
INFO  -- [2018-07-03 01:12:00.190] -- Degap and mask finished in 5.3287573 seconds 
INFO  -- [2018-07-03 01:12:00.354] -- Get entropy for masked user seqs finished in 0.1635697 seconds 
DEBUG -- [2018-07-03 01:12:00.366] -- Running: /bin/gunzip -c /home/ZetaHunter/assets/silva.gold.align.gz > /tmp/d20180703_1_cte5v9/tmp/silva.gold.align 
DEBUG -- [2018-07-03 01:12:01.818] -- Running: /home/ZetaHunter/bin/linux/mothur '#chimera.uchime(fasta=/tmp/d20180703_1_cte5v9/tmp/Gold_release3.fasta, reference=/tmp/d20180703_1_cte5v9/tmp/silva.gold.align, outputdir=/tmp/d20180703_1_cte5v9, processors=4)' >> /tmp/d20180703_1_cte5v9/log/ZH_2018_07_03_01_11.log.mothur.txt 2>&1 
FATAL -- [2018-07-03 01:12:02.026] -- ERROR: non-zero exit status (127) -- Stack Trace: /home/ZetaHunter/lib/abort_if/abort_if.rb:30:in `abort_if' | /usr/local/bundle/gems/abort_if-0.2.0/lib/abort_if.rb:97:in `abort_unless' | /home/ZetaHunter/lib/core_extensions/process/process.rb:36:in `run_it!' | /home/ZetaHunter/lib/utils/utils.rb:454:in `block in run_uchime' | /home/ZetaHunter/lib/utils/utils.rb:443:in `each' | /home/ZetaHunter/lib/utils/utils.rb:443:in `run_uchime' | /home/ZetaHunter/zeta_hunter.rb:485:in `block in <main>' | /home/ZetaHunter/lib/core_extensions/time/time.rb:29:in `time_it' | /home/ZetaHunter/zeta_hunter.rb:484:in `<main>' 
```

Run without chimera checking:
```
seanmcastersMBP:Desktop sean$ run_zeta_hunter -i Gold_release3.fasta -o ZH_GOLDTEST -t 4 --no-check-chimeras



RUNNING COMMAND: docker pull mooreryan/zetahunter


Using default tag: latest
latest: Pulling from mooreryan/zetahunter
Digest: sha256:534ff7c384915c104d55f503d9e6373dbc0911ec65860f383ba949290505980f
Status: Image is up to date for mooreryan/zetahunter:latest



RUNNING COMMAND: docker run -v "$HOME:$HOME" mooreryan/zetahunter ruby /home/ZetaHunter/zeta_hunter.rb -i '/Users/sean/Desktop/Gold_release3.fasta' -o '/Users/sean/Desktop/ZH_GOLDTEST' -t '4' --no-check-chimeras


DEBUG -- [2018-07-03 01:14:10.860] -- Version: 1.0.0, Copyright: 2016 - 2018 Ryan Moore, Contact: moorer@udel.edu, Website: https://github.com/mooreryan/ZetaHunter, License: GPLv3 
INFO  -- [2018-07-03 01:14:10.860] -- Temporary log file location: /ZH_2018_07_03_01_14.log.zh.txt. If ZetaHunter fails to complete, the log will be here. 
DEBUG -- [2018-07-03 01:14:10.860] -- ARGV: ["-i", "/Users/sean/Desktop/Gold_release3.fasta", "-o", "/Users/sean/Desktop/ZH_GOLDTEST", "-t", "4", "--no-check-chimeras"] 
DEBUG -- [2018-07-03 01:14:10.860] -- Command line opts: {:inaln=>["/Users/sean/Desktop/Gold_release3.fasta"], :outdir=>"/Users/sean/Desktop/ZH_GOLDTEST", :threads=>4, :db_otu_info=>"/home/ZetaHunter/assets/db_otu_info.txt", :mask=>"/home/ZetaHunter/assets/mask.fa.gz", :db_seqs=>"/home/ZetaHunter/assets/db_seqs.fa.gz", :mothur=>"/home/ZetaHunter/bin/linux/mothur", :sortmerna=>"/home/ZetaHunter/bin/linux/sortmerna", :indexdb_rna=>"/home/ZetaHunter/bin/linux/indexdb_rna", :cluster_method=>"average", :otu_percent=>97, :check_chimeras=>false, :base=>"ZH_2018_07_03_01_14", :debug=>false, :version=>false, :help=>false, :inaln_given=>true, :outdir_given=>true, :threads_given=>true, :check_chimeras_given=>true} 
INFO  -- [2018-07-03 01:14:10.903] -- Create needed directories finished in 0.0015665 seconds 
DEBUG -- [2018-07-03 01:14:10.903] -- Sample to fname map: /tmp/d20180703_1_5fkz5h/misc/ZH_2018_07_03_01_14.sample_id_to_fname.txt 
INFO  -- [2018-07-03 01:14:10.904] -- Write sample to file name map finished in 0.000545 seconds 
INFO  -- [2018-07-03 01:14:10.906] -- Unzip if needed finished in 0.0020587 seconds 
INFO  -- [2018-07-03 01:14:16.540] -- Process input data finished in 5.6337509 seconds 
INFO  -- [2018-07-03 01:14:16.545] -- Read entropy info finished in 0.0049118 seconds 
INFO  -- [2018-07-03 01:14:16.550] -- Read db OTU metadata finished in 0.0045228 seconds 
INFO  -- [2018-07-03 01:14:16.564] -- Num mask bases: 1282 
INFO  -- [2018-07-03 01:14:16.564] -- Read mask info finished in 0.0140253 seconds 
INFO  -- [2018-07-03 01:14:21.154] -- Update shared gap posns with db seqs finished in 4.5899942 seconds 
INFO  -- [2018-07-03 01:14:21.155] -- Read outgroups finished in 0.0003636 seconds 
INFO  -- [2018-07-03 01:14:31.137] -- Degap and mask finished in 5.2495319 seconds 
INFO  -- [2018-07-03 01:14:31.292] -- Get entropy for masked user seqs finished in 0.1548585 seconds 
DEBUG -- [2018-07-03 01:14:33.828] -- Aligned DB seqs: /tmp/d20180703_1_5fkz5h/db_seqs.fa.gz 
DEBUG -- [2018-07-03 01:14:33.828] -- Unaligned DB seqs: /tmp/d20180703_1_5fkz5h/tmp/db_seqs.unaln.fa 
INFO  -- [2018-07-03 01:14:33.828] -- Unalign DB seqs if needed finished in 2.5361616 seconds 
INFO  -- [2018-07-03 01:14:35.848] -- Unalign input seqs finished in 2.0191388 seconds 
DEBUG -- [2018-07-03 01:14:35.848] -- Running: /home/ZetaHunter/bin/linux/indexdb_rna --ref /tmp/d20180703_1_5fkz5h/tmp/db_seqs.unaln.fa,/tmp/d20180703_1_5fkz5h/tmp/db_seqs.unaln.idx 
INFO  -- [2018-07-03 01:14:36.283] -- Build SortMeRNA index finished in 0.4353311 seconds 
DEBUG -- [2018-07-03 01:14:36.284] -- Running: /home/ZetaHunter/bin/linux/sortmerna -a 4 --ref /tmp/d20180703_1_5fkz5h/tmp/db_seqs.unaln.fa,/tmp/d20180703_1_5fkz5h/tmp/db_seqs.unaln.idx --reads /tmp/d20180703_1_5fkz5h/tmp/ZH_2018_07_03_01_14.unaln.fa --aligned /tmp/d20180703_1_5fkz5h/ZH_2018_07_03_01_14.unlan.sortme_blast --blast '1 qcov' --num_alignments 0 
DEBUG -- [2018-07-03 01:16:44.984] -- SortMeRNA blast: /tmp/d20180703_1_5fkz5h/ZH_2018_07_03_01_14.unlan.sortme_blast.blast 
INFO  -- [2018-07-03 01:16:44.985] -- SortMeRNA finished in 128.7010225 seconds 
INFO  -- [2018-07-03 01:16:45.695] -- Read SortMeRNA blast finished in 0.7099855 seconds 
DEBUG -- [2018-07-03 01:16:45.700] -- Closest DB seqs: /tmp/d20180703_1_5fkz5h/misc/ZH_2018_07_03_01_14.closest_db_seqs.txt 
DEBUG -- [2018-07-03 01:16:45.700] -- Distance based OTU calls written to /tmp/d20180703_1_5fkz5h/otu_calls/ZH_2018_07_03_01_14.otu_calls.closed_ref.txt 
INFO  -- [2018-07-03 01:16:45.700] -- Write closest ref seqs and OTU calls finished in 0.0046142 seconds 
INFO  -- [2018-07-03 01:16:45.701] -- We will cluster this file: /tmp/d20180703_1_5fkz5h/tmp/cluster_me.fa 
INFO  -- [2018-07-03 01:16:45.701] -- Write masked, combined fasta finished in 0.00156 seconds 
DEBUG -- [2018-07-03 01:16:45.701] -- Running: /home/ZetaHunter/bin/linux/mothur '#dist.seqs(fasta=/tmp/d20180703_1_5fkz5h/tmp/cluster_me.fa, outputdir=/tmp/d20180703_1_5fkz5h/tmp, output=lt, processors=4)' >> /tmp/d20180703_1_5fkz5h/log/ZH_2018_07_03_01_14.log.mothur.txt 2>&1 
FATAL -- [2018-07-03 01:16:45.777] -- ERROR: non-zero exit status (127) -- Stack Trace: /home/ZetaHunter/lib/abort_if/abort_if.rb:30:in `abort_if' | /usr/local/bundle/gems/abort_if-0.2.0/lib/abort_if.rb:97:in `abort_unless' | /home/ZetaHunter/lib/core_extensions/process/process.rb:36:in `run_it!' | /home/ZetaHunter/lib/utils/utils.rb:683:in `run_mothur_distance' | /home/ZetaHunter/zeta_hunter.rb:554:in `block in <main>' | /home/ZetaHunter/lib/core_extensions/time/time.rb:29:in `time_it' | /home/ZetaHunter/zeta_hunter.rb:553:in `<main>' 
```

**Comment by seanmcallister** [comment]
Problem was just in Docker build. Mothur version we are using requires libreadline6, but the new docker build was trying to use v.7. Fixed with update to mothur that doesn't require readline.

**Comment by mooreryan** [comment]
These will have the fix.

901853660dfe11cab08cc9c62a228c719bcf4361

https://github.com/mooreryan/ZetaHunter/releases/tag/v1.0.2
